
import os

filepath = r'c:\Users\chank\OneDrive\Documents\UltronSolar\src\lib\translations.ts'
with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

replacements = {
    "      home: 'Home'": "      home: 'होम'",
    "      services: 'Services'": "      services: 'सेवायें'",
    "      products: 'Products'": "      products: 'उत्पाद'",
    "      about: 'About'": "      about: 'हमारे बारे में'",
    "      blog: 'Blog'": "      blog: 'ब्लॉग'",
    "      contact: 'Contact'": "      contact: 'संपर्क'",
    "      menu: 'Menu'": "      menu: 'मेनू'",
    "      residential: 'Residential'": "      residential: 'आवासीय'",
    "      agriculture: 'Agriculture'": "      agriculture: 'कृषि'",
    "      commercial: 'Commercial'": "      commercial: 'व्यावसायिक'",
    "      getQuote: 'Get Free Quote'": "      getQuote: 'फ्री कोट प्राप्त करें'",
    "      title: 'Power Your Future'": "      title: 'अपने भविष्य को शक्ति दें'",
    "      titleHighlight: 'With Solar Energy'": "      titleHighlight: 'सौर ऊर्जा के साथ'",
    "      subtitle: 'Premium rooftop solar solutions for homes, farms, and businesses in Dhule & North Maharashtra.'": "      subtitle: 'धुले और उत्तर महाराष्ट्र में घरों, खेतों और व्यवसायों के लिए प्रीमियम रूफटॉप सोलर समाधान।'",
    "      priceNote: '⚡ Systems starting at ₹99,999'": "      priceNote: '⚡ ₹99,999 से शुरू होने वाली प्रणाली'",
    "      serving: 'Serving Dhule, Jalgaon & North Maharashtra'": "      serving: 'धुले, जलगाँव और उत्तर महाराष्ट्र में सेवा दे रहे हैं'",
    "      title: 'Professional Solar Services'": "      title: 'पेशेवर सौर सेवाएं'",
    "      subtitle: 'Comprehensive solar solutions tailored to meet your unique needs with quality and reliability.'": "      subtitle: 'गुणवत्ता और विश्वसनीयता के साथ आपकी विशिष्ट आवश्यकताओं को पूरा करने के लिए तैयार व्यापक सौर समाधान।'",
    "        title: 'Expert Installations'": "        title: 'विशेषज्ञ स्थापना'",
    "        description: 'We specialize in offering premium solar panel installation services for homes, businesses, apartments, and farms. Our team of experts is skilled in effective installation and deeply knowledgeable about optimizing the positioning of solar panels to maximize sunlight exposure and energy generation.'": "        description: 'हम घरों, व्यवसायों, अपार्टमेंट और खेतों के लिए प्रीमियम सौर पैनल स्थापना सेवाएं प्रदान करने में माहिर हैं। हमारी विशेषज्ञों की टीम प्रभावी स्थापना में कुशल है और सौर पैनलों की स्थिति के अनुकूलन के बारे में गहराई से जानती है ताकि सूर्य के प्रकाश का अधिकतम लाभ उठाया जा सके।'",
    "        title: 'Flexible Payment Options'": "        title: 'लचीले भुगतान विकल्प'",
    "        description: 'We understand that every customer has different preferences when it comes to payment. We provide assistance for bank loans with streamlined processing specifically for solar projects. Additionally, we guide our customers in availing government subsidies designed to support the adoption of solar technology.'": "        description: 'हम समझते हैं कि भुगतान के मामले में हर ग्राहक की अलग-अलग प्राथमिकताएं होती हैं। हम सौर परियोजनाओं के लिए बैंक ऋण के लिए सहायता प्रदान करते हैं। इसके अतिरिक्त, हम ग्राहकों को सौर तकनीक अपनाने के लिए सरकारी सब्सिडी का लाभ उठाने में मार्गदर्शन करते हैं।'",
    "        title: 'Complete EPC Solutions'": "        title: 'पूर्ण EPC समाधान'",
    "        description: 'At Ultron Power Systems, we offer complete solar EPC (Engineering, Procurement, and Construction) solutions. From initial design and engineering to procurement of high-quality solar equipment and construction of the solar power system, we handle every aspect of the project.'": "        description: 'अल्ट्रॉन पावर सिस्टम्स में, हम पूर्ण सौर EPC (इंजीनियरिंग, खरीद और निर्माण) समाधान प्रदान करते हैं। डिजाइन और इंजीनियरिंग से लेकर उच्च गुणवत्ता वाले सौर उपकरणों की खरीद और सौर ऊर्जा प्रणाली के निर्माण तक, हम परियोजना के हर पहलू को संभालते हैं।'",
    "        title: 'Peace of Mind Warranty'": "        title: 'शांति की गारंटी वाली वारंटी'",
    "        description: 'We stand behind the quality of our work and the products we install. That\\'s why we offer a comprehensive warranty on all our solar installations as per terms and conditions of principal suppliers of solar panels and materials. With us, you can have peace of mind knowing that your solar system is protected.'": "        description: 'हम अपने काम की गुणवत्ता और हमारे द्वारा स्थापित उत्पादों के पीछे खड़े हैं। इसीलिए हम प्रमुख सौर पैनल और सामग्री आपूर्तिकर्ताओं के नियमों और शर्तों के अनुसार अपनी सभी सौर स्थापनाओं पर व्यापक वारंटी प्रदान करते हैं।'",
    "      title: 'Why Ultron Power Systems?'": "      title: 'अल्ट्रॉन पावर सिस्टम्स क्यों?'",
    "      yearsExperience: 'Years Experience'": "      yearsExperience: 'वर्षों का अनुभव'",
    "        description: 'From initial design and engineering to procurement and construction, we handle every aspect of your solar project.'": "        description: 'प्रारंभिक डिजाइन और इंजीनियरिंग से लेकर खरीद और निर्माण तक, हम आपकी सौर परियोजना के हर पहलू को संभालते हैं।'",
    "        title: 'Multiple Applications'": "        title: 'एकाधिक अनुप्रयोग'",
    "        description: 'We serve residential properties, commercial businesses, industrial facilities, farms, apartments, and solar parking lots with customized solutions.'": "        description: 'हम आवासीय संपत्तियों, वाणिज्यिक व्यवसायों, औद्योगिक सुविधाओं, खेतों, अपार्टमेंट और सोलर पार्किंग लॉट्स के लिए अनुकूलित समाधान प्रदान करते हैं।'",
    "        title: 'High-Quality & Reliable'": "        title: 'उच्च-गुणवत्ता और विश्वसनीय'",
    "        description: 'Our full-service approach ensures peace of mind with premium equipment and expert installation.'": "        description: 'हमारा पूर्ण-सेवा दृष्टिकोण प्रीमियम उपकरणों और विशेषज्ञ स्थापना के साथ मानसिक शांति सुनिश्चित करता है।'",
    "        title: 'Customized Solutions'": "        title: 'अनुकूलित समाधान'",
    "        description: 'We tailor solutions to meet the unique needs of each customer, ensuring optimal performance and value.'": "        description: 'हम प्रत्येक ग्राहक की अद्वितीय आवश्यकताओं को पूरा करने के लिए समाधान तैयार करते हैं, जो इष्टतम प्रदर्शन और मूल्य सुनिश्चित करते हैं।'",
    "        title: 'About Us'": "        title: 'हमारे बारे में'",
    "        description: 'Ultron Power Systems is the go-to provider of solar power systems and products. Our team of experts is dedicated to customizing solutions tailored to meet the unique needs of each customer. From rooftop installations to farm, residential, business, and solar carport applications, we have you covered.'": "        description: 'अल्ट्रॉन पावर सिस्टम्स सौर ऊर्जा प्रणालियों और उत्पादों का प्रमुख प्रदाता है। हमारी विशेषज्ञों की टीम प्रत्येक ग्राहक की विशिष्ट आवश्यकताओं के लिए समाधान तैयार करने के लिए समर्पित है।'",
    "        description2: 'Our high-quality, reliable and full-service approach ensures peace of mind. Contact us today to learn how we can power your future with solar technology.'": "        description2: 'हमारा उच्च-गुणवत्ता, विश्वसनीय और पूर्ण-सेवा दृष्टिकोण मानसिक शांति सुनिश्चित करता है। यह जानने के लिए आज ही हमसे संपर्क करें कि हम आपके भविष्य को सौर तकनीक से कैसे रोशन कर सकते हैं।'",
    "        contactButton: 'Contact Us Today'": "        contactButton: 'आज ही हमसे संपर्क करें'",
    "      description: 'Empowering Maharashtra with sustainable solar energy solutions. Quality installation, reliable support, and guaranteed savings.'": "      description: 'टिकाऊ सौर ऊर्जा समाधानों के साथ महाराष्ट्र को सशक्त बनाना। गुणवत्तापूर्ण स्थापना, विश्वसनीय सहायता और गारंटीड बचत।'",
    "      quickLinks: 'Quick Links'": "      quickLinks: 'क्विक लिंक्स'",
    "      services: 'Our Services'": "      services: 'हमारी सेवाएं'",
    "      contact: 'Contact'": "      contact: 'संपर्क'",
    "      followUs: 'Follow Us'": "      followUs: 'हमें फॉलो करें'",
    "      copyright: '© 2024 Ultron Power Systems. All rights reserved.'": "      copyright: '© 2024 अल्ट्रॉन पावर सिस्टम्स। सर्वाधिकार सुरक्षित।'",
    "        home: 'Home'": "        home: 'होम'",
    "        services: 'Services'": "        services: 'सेवायें'",
    "        products: 'Products'": "        products: 'उत्पाद'",
    "        projects: 'Projects'": "        projects: 'प्रोजेक्ट्स'",
    "        contact: 'Contact Us'": "        contact: 'संपर्क करें'",
    "        residential: 'Residential Rooftop'": "        residential: 'आवासीय रूफटॉप'",
    "        commercial: 'Commercial Solar'": "        commercial: 'वाणिज्यिक सोलर'",
    "        pumps: 'Solar Water Pumps'": "        pumps: 'सोलर वाटर पंप'",
    "        industrial: 'Industrial Solutions'": "        industrial: 'औद्योगिक समाधान'",
    "        maintenance: 'Operation & Maintenance'": "        maintenance: 'संचालन और रखरखाव'",
    "        title: 'Stay Updated'": "        title: 'अपडेट रहें'",
    "        description: 'Subscribe to our newsletter for latest solar trends and exclusive offers.'": "        description: 'नवीनतम सौर रुझानों और विशेष ऑफ़र के लिए हमारे न्यूज़लेटर की सदस्यता लें।'",
    "        placeholder: 'Enter your email'": "        placeholder: 'अपना ईमेल दर्ज करें'",
    "        button: 'Subscribe'": "        button: 'सब्सक्राइब'",
    "        privacy: 'Privacy Policy'": "        privacy: 'प्राइवेसी पॉलिसी'",
    "        cookies: 'Cookie Policy'": "        cookies: 'कुकी पॉलिसी'",
    "        cookieSettings: 'Cookie Settings'": "        cookieSettings: 'कुकी सेटिंग्स'",
    "        sitemap: 'Sitemap'": "        sitemap: 'साइटमैप'",
    "      title: 'Frequently Asked Questions'": "      title: 'अक्सर पूछे जाने वाले प्रश्न'",
    "      subtitle: 'Common questions about solar installation in Maharashtra'": "      subtitle: 'महाराष्ट्र में सौर स्थापना के बारे में सामान्य प्रश्न'",
    "          question: 'How much does a 3kW solar system cost in Dhule?'": "          question: 'धुले में 3kW सौर प्रणाली की कीमत क्या है?'",
    "          answer: 'A standard 3kW on-grid solar system typically ranges from ₹1.8 Lakh to ₹2.2 Lakh before subsidy. Prices vary based on component brands (panels, inverters) and site conditions. Contact us for a precise quote tailored to your roof.'": "          answer: 'एक मानक 3kW ऑन-ग्रिड सौर प्रणाली आमतौर पर सब्सिडी से पहले ₹1.8 लाख से ₹2.2 लाख तक होती है। कीमतें कंपोनेंट ब्रांड (पैनल, इन्वर्टर) और साइट की स्थितियों के आधार पर भिन्न होती हैं। सटीक कोट के लिए हमसे संपर्क करें।'",
    "          question: 'What subsidies are available in Maharashtra?'": "          question: 'महाराष्ट्र में कौन सी सब्सिडी उपलब्ध हैं?'",
    "          answer: 'Under the PM Surya Ghar Muft Bijli Yojana, residential consumers can get subsidies up to ₹30,000 per kW for the first 2kW and ₹18,000 for additional capacity up to 3kW. We assist with the entire application process.'": "          answer: 'पीएम सूर्य घर मुफ्त बिजली योजना के तहत, आवासीय उपभोक्ता पहले 2kW के लिए ₹30,000 प्रति kW और 3kW तक की अतिरिक्त क्षमता के लिए ₹18,000 की सब्सिडी प्राप्त कर सकते हैं। हम पूरी आवेदन प्रक्रिया में सहायता करते हैं।'",
    "          question: 'How many units will a 3kW system generate?'": "          question: '3kW की प्रणाली कितनी यूनिट बिजली बनाएगी?'",
    "          answer: 'In Maharashtra\\'s climate, a 3kW system generates approximately 12-15 units per day, or about 360-450 units per month, depending on sunlight availability and panel efficiency.'": "          answer: 'महाराष्ट्र की जलवायु में, 3kW की प्रणाली प्रतिदिन लगभग 12-15 यूनिट, या प्रति माह लगभग 360-450 यूनिट बिजली बनाती है।'",
    "          question: 'What is the warranty on your solar systems?'": "          question: 'आपकी सौर प्रणालियों पर क्या वारंटी है?'",
    "          answer: 'We provide a standard 25-year performance warranty on solar panels and a 5-10 year warranty on inverters, backed by the respective manufacturers. Our installation workmanship is also guaranteed.'": "          answer: 'हम सौर पैनलों पर मानक 25 साल की प्रदर्शन वारंटी और इन्वर्टर पर 5-10 साल की वारंटी प्रदान करते हैं। हमारी स्थापना कारीगरी की भी गारंटी है।'",
    "          question: 'Do I need batteries for my solar system?'": "          question: 'क्या मुझे अपने सोलर सिस्टम के लिए बैटरी की जरूरत है?'",
    "          answer: 'For on-grid systems (most common in cities), batteries are not required as you export excess power to the grid. Off-grid or hybrid systems require batteries for backup during power cuts.'": "          answer: 'ऑन-ग्रिड सिस्टम (शहरों में सबसे आम) के लिए, बैटरी की आवश्यकता नहीं होती है क्योंकि आप ग्रिड को अतिरिक्त बिजली निर्यात करते हैं। ऑफ-ग्रिड सिस्टम के लिए बैटरी की आवश्यकता होती है।'",
    "          question: 'How much roof space is required?'": "          question: 'कितनी छत की जगह की आवश्यकता है?'",
    "          answer: 'Approximately 100 sq. ft. of shadow-free area is required for every 1kW of solar capacity. So, a 3kW system would need about 300 sq. ft. of clear roof space.'": "          answer: 'प्रत्येक 1kW सौर क्षमता के लिए लगभग 100 वर्ग फुट छाया-मुक्त क्षेत्र की आवश्यकता होती है। इसलिए, 3kW की प्रणाली को लगभग 300 वर्ग फुट खाली छत की जगह की आवश्यकता होगी।'",
    "      title: 'Get in Touch'": "      title: 'संपर्क करें'",
    "      subtitle: 'Ready to go solar? Contact us today for a free consultation and quote.'": "      subtitle: 'सोलर अपनाने के लिए तैयार हैं? फ्री परामर्श और कोट के लिए आज ही हमसे संपर्क करें।'",
    "      formTitle: 'Request a Free Quote'": "      formTitle: 'फ्री कोट का अनुरोध करें'",
    "        name: 'Name'": "        name: 'नाम'",
    "        phone: 'Phone Number'": "        phone: 'फोन नंबर'",
    "        city: 'City'": "        city: 'शहर'",
    "        email: 'Email (Optional)'": "        email: 'ईमेल (वैकल्पिक)'",
    "        requirement: 'Requirement'": "        requirement: 'जरूरत'",
    "        message: 'Message (Optional)'": "        message: 'संदेश (वैकल्पिक)'",
    "        submit: 'Get Free Quote'": "        submit: 'फ्री कोट प्राप्त करें'",
    "        submitting: 'Sending...'": "        submitting: 'भेज रहे हैं...'",
    "        success: 'Thank you! Your request has been sent.'": "        success: 'धन्यवाद! आपका अनुरोध भेज दिया गया है।'",
    "        successSubtext: 'We will contact you within 24 hours.'": "        successSubtext: 'हम 24 घंटे के भीतर आपसे संपर्क करेंगे।'",
    "        error: 'Something went wrong. Please try again or call us directly.'": "        error: 'कुछ गलत हो गया। कृपया पुन: प्रयास करें या हमें सीधे कॉल करें।'",
    "        namePlaceholder: 'Your Name'": "        namePlaceholder: 'आपका नाम'",
    "        phonePlaceholder: '10-digit mobile'": "        phonePlaceholder: '10-अंकों का मोबाइल'",
    "        cityPlaceholder: 'Dhule, Nashik, etc.'": "        cityPlaceholder: 'धुले, नाशिक, आदि।'",
    "        emailPlaceholder: 'your@email.com'": "        emailPlaceholder: 'your@email.com'",
    "        messagePlaceholder: 'Any specific requirements or questions?'": "        messagePlaceholder: 'कोई विशेष आवश्यकता या प्रश्न?'",
    "        'Home Solar System'": "        'घरेलू सोलर सिस्टम'",
    "        'Commercial Solar System'": "        'वाणिज्यिक सोलर सिस्टम'",
    "        'Solar Water Pump'": "        'सोलर वाटर पंप'",
    "        'Industrial Solar Solution'": "        'औद्योगिक सोलर समाधान'",
    "        'Solar UPS/Inverter'": "        'सोलर यूपीएस/इन्वर्टर'",
    "        'Other'": "        'अन्य'",
    "        title: 'Contact Information'": "        title: 'संपर्क जानकारी'",
    "        visitUs: 'Visit Us'": "        visitUs: 'हमसे मिलने आएं'",
    "        callUs: 'Call Us'": "        callUs: 'हमें कॉल करें'",
    "        emailUs: 'Email Us'": "        emailUs: 'हमें ईमेल करें'",
    "        { title: 'Homeowners', getQuote: 'Get Quote →' }": "        { title: 'घर के मालिक', getQuote: 'कोट प्राप्त करें →' }",
    "        { title: 'Offices & Shops', getQuote: 'Get Quote →' }": "        { title: 'कार्यालय और दुकानें', getQuote: 'कोट प्राप्त करें →' }",
    "        { title: 'Industries', getQuote: 'Get Quote →' }": "        { title: 'उद्योग', getQuote: 'कोट प्राप्त करें →' }",
    "        { title: 'Farms & Pumps', getQuote: 'Get Quote →' }": "        { title: 'खेत और पंप', getQuote: 'कोट प्राप्त करें →' }",
    "        { title: 'Apartments', getQuote: 'Get Quote →' }": "        { title: 'अपार्टमेंट', getQuote: 'कोट प्राप्त करें →' }",
    "        title: 'Commercial & Industrial Solutions'": "        title: 'वाणिज्यिक और औद्योगिक समाधान'",
    "        description: 'Looking for solar solutions for your business or industry? We provide customized solar systems designed to reduce operational costs and improve sustainability.'": "        description: 'अपने व्यवसाय या उद्योग के लिए सौर समाधान खोज रहे हैं? हम परिचालन लागत को कम करने और स्थिरता में सुधार करने के लिए डिज़ाइन किए गए अनुकूलित सौर प्रणाली प्रदान करते हैं।'",
    "      title: 'Our Products'": "      title: 'हमारे उत्पाद'",
    "      subtitle: 'Premium quality solar equipment for residential, commercial, and agricultural use.'": "      subtitle: 'आवासीय, वाणिज्यिक और कृषि उपयोग के लिए प्रीमियम गुणवत्ता वाले सौर उपकरण।'",
    "      viewDetails: 'View Details'": "      viewDetails: 'विवरण देखें'",
    "          title: 'Solar Water Pump'": "          title: 'सौर जल पंप'",
    "          description: 'Reliable solar powered water pump systems for agriculture and irrigation needs.'": "          description: 'कृषि और सिंचाई की जरूरतों के लिए विश्वसनीय सौर ऊर्जा संचालित जल पंप प्रणाली।'",
    "          title: 'Solar Power UPS'": "          title: 'सोलर पावर यूपीएस'",
    "          description: 'Uninterrupted power supply solutions for homes and businesses.'": "          description: 'घरों और व्यवसायों के लिए निर्बाध बिजली आपूर्ति समाधान।'",
    "          title: 'Voltage Stabilizer'": "          title: 'वॉल्टेज स्टेबलाइजर'",
    "          description: 'Servo controlled voltage stabilizers for equipment protection.'": "          description: 'उपकरणों की सुरक्षा के लिए सर्वो नियंत्रित वोल्टेज स्टेबलाइजर।'",
    "          title: 'Solar Street Lights'": "          title: 'सोलर स्ट्रीट लाइट्स'",
    "          description: 'Automatic, energy-efficient lighting for streets and campuses.'": "          description: 'सड़कों और परिसरों के लिए स्वचालित, ऊर्जा-कुशल प्रकाश व्यवस्था।'",
    "          title: 'Rooftop Solar Panels'": "          title: 'रूफटॉप सोलर पैनल'",
    "          description: 'High-efficiency solar panels for maximum energy generation.'": "          description: 'अधिकतम ऊर्जा उत्पादन के लिए उच्च दक्षता वाले सौर पैनल।'",
    "          title: 'Solar Water Heater'": "          title: 'सोलर वाटर हीटर'",
    "          description: 'Cost-effective water heating solutions for all seasons.'": "          description: 'सभी मौसमों के लिए लागत प्रभावी जल तापन समाधान।'",
    "      readMore: 'Read More'": "      readMore: 'और पढ़ें'",
    "      learnMore: 'Learn More'": "      learnMore: 'अधिक जानें'",
    "      getStarted: 'Get Started'": "      getStarted: 'शुरू करें'",
}

filepath = r'c:\Users\chank\OneDrive\Documents\UltronSolar\src\lib\translations.ts'
with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open(filepath, 'w', encoding='utf-8') as f:
    for i, line in enumerate(lines):
        if i >= 838 and i <= 1125: # hi section
            for old, new in replacements.items():
                if old in line:
                    line = line.replace(old, new)
        f.write(line)
